language: java

sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
    email:
      recipients:
        - maksimus.s@mail.ru
      on_success: never # default: change
      on_failure: always # default: always